from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from datetime import *
import json

app = FastAPI()

origins = [
    "http://localhost:3000",
    "localhost:3000"
]
today = str(date.today())
hour = datetime.now().hour


app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"]
)


@app.get("/", tags=["root"])
async def read_root() -> dict:
    return {"message": "Welcome to your Weather App."}


@app.get("/api/getcurrentWeather")
async def getcurrentWeather():
    forecastDate = data["forecast"]["forecastday"]
    for i in forecastDate:
        if i["date"] == today:
            return (i["hour"][hour])

@app.get("/api/dayWeather/")
async def getForecast(days: int = 1):
    wData = []
    ranges = data["forecast"]["forecastday"][0:days]
    for day in ranges:
        wData.append(day["day"])
    return wData

@app.get("/api/getHour")
async def getHour():
    
    forecastDate = data["forecast"]["forecastday"]
    for i in forecastDate:
        if i["date"] == today:
            return i["hour"]
    else: 
        return {"error: Date Not Found", "Code:404"}





data = {
    "location": {
        "name": "New York",
        "region": "New York",
        "country": "United States of America",
        "lat": 40.71,
        "lon": -74.01,
        "tz_id": "America/New_York",
        "localtime_epoch": 1665339714,
        "localtime": "2022-10-09 14:21"
    },
    "current": {
        "last_updated_epoch": 1665339300,
        "last_updated": "2022-10-09 14:15",
        "temp_c": 15.6,
        "temp_f": 60.1,
        "is_day": 1,
        "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 16.1,
        "wind_kph": 25.9,
        "wind_degree": 240,
        "wind_dir": "WSW",
        "pressure_mb": 1020.0,
        "pressure_in": 30.11,
        "precip_mm": 0.0,
        "precip_in": 0.0,
        "humidity": 40,
        "cloud": 25,
        "feelslike_c": 15.6,
        "feelslike_f": 60.1,
        "vis_km": 16.0,
        "vis_miles": 9.0,
        "uv": 4.0,
        "gust_mph": 16.6,
        "gust_kph": 26.6
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2022-10-16",
                "date_epoch": 1665273600,
                "day": {
                    "maxtemp_c": 15.5,
                    "maxtemp_f": 59.9,
                    "mintemp_c": 5.0,
                    "mintemp_f": 41.0,
                    "avgtemp_c": 10.5,
                    "avgtemp_f": 50.8,
                    "maxwind_mph": 14.3,
                    "maxwind_kph": 23.0,
                    "totalprecip_mm": 0.0,
                    "totalprecip_in": 0.0,
                    "avgvis_km": 10.0,
                    "avgvis_miles": 6.0,
                    "avghumidity": 78.0,
                    "daily_will_it_rain": 0,
                    "daily_chance_of_rain": 0,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "uv": 4.0
                },
                "astro": {
                    "sunrise": "07:01 AM",
                    "sunset": "06:25 PM",
                    "moonrise": "06:34 PM",
                    "moonset": "06:32 AM",
                    "moon_phase": "Waxing Gibbous",
                    "moon_illumination": "95"
                },
                "hour": [
                    {
                        "time_epoch": 1665288000,
                        "time": "2022-10-09 00:00",
                        "temp_c": 9.5,
                        "temp_f": 49.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.9,
                        "wind_kph": 11.2,
                        "wind_degree": 282,
                        "wind_dir": "WNW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.15,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 85,
                        "cloud": 0,
                        "feelslike_c": 7.9,
                        "feelslike_f": 46.2,
                        "windchill_c": 7.9,
                        "windchill_f": 46.2,
                        "heatindex_c": 9.5,
                        "heatindex_f": 49.1,
                        "dewpoint_c": 7.1,
                        "dewpoint_f": 44.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.2,
                        "gust_kph": 14.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665291600,
                        "time": "2022-10-09 01:00",
                        "temp_c": 9.0,
                        "temp_f": 48.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 7.6,
                        "wind_kph": 12.2,
                        "wind_degree": 271,
                        "wind_dir": "W",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.14,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 85,
                        "cloud": 9,
                        "feelslike_c": 7.4,
                        "feelslike_f": 45.3,
                        "windchill_c": 7.4,
                        "windchill_f": 45.3,
                        "heatindex_c": 9.0,
                        "heatindex_f": 48.2,
                        "dewpoint_c": 6.7,
                        "dewpoint_f": 44.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.1,
                        "gust_kph": 16.2,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665295200,
                        "time": "2022-10-09 02:00",
                        "temp_c": 8.6,
                        "temp_f": 47.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.2,
                        "wind_kph": 14.8,
                        "wind_degree": 294,
                        "wind_dir": "WNW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.14,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 85,
                        "cloud": 0,
                        "feelslike_c": 6.9,
                        "feelslike_f": 44.4,
                        "windchill_c": 6.9,
                        "windchill_f": 44.4,
                        "heatindex_c": 8.6,
                        "heatindex_f": 47.5,
                        "dewpoint_c": 6.3,
                        "dewpoint_f": 43.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.9,
                        "gust_kph": 19.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665298800,
                        "time": "2022-10-09 03:00",
                        "temp_c": 8.1,
                        "temp_f": 46.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 10.3,
                        "wind_kph": 16.6,
                        "wind_degree": 313,
                        "wind_dir": "NW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.15,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 86,
                        "cloud": 0,
                        "feelslike_c": 6.1,
                        "feelslike_f": 43.0,
                        "windchill_c": 6.1,
                        "windchill_f": 43.0,
                        "heatindex_c": 8.1,
                        "heatindex_f": 46.6,
                        "dewpoint_c": 5.9,
                        "dewpoint_f": 42.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.2,
                        "gust_kph": 21.2,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665302400,
                        "time": "2022-10-09 04:00",
                        "temp_c": 7.7,
                        "temp_f": 45.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.5,
                        "wind_kph": 13.7,
                        "wind_degree": 308,
                        "wind_dir": "NW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.15,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 87,
                        "cloud": 0,
                        "feelslike_c": 5.4,
                        "feelslike_f": 41.7,
                        "windchill_c": 5.4,
                        "windchill_f": 41.7,
                        "heatindex_c": 7.7,
                        "heatindex_f": 45.9,
                        "dewpoint_c": 5.7,
                        "dewpoint_f": 42.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.2,
                        "gust_kph": 18.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665306000,
                        "time": "2022-10-09 05:00",
                        "temp_c": 5.5,
                        "temp_f": 41.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
                            "code": 1135
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 284,
                        "wind_dir": "WNW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.16,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 98,
                        "cloud": 100,
                        "feelslike_c": 3.2,
                        "feelslike_f": 37.8,
                        "windchill_c": 3.2,
                        "windchill_f": 37.8,
                        "heatindex_c": 5.5,
                        "heatindex_f": 41.9,
                        "dewpoint_c": 5.2,
                        "dewpoint_f": 41.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.5,
                        "gust_kph": 13.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665309600,
                        "time": "2022-10-09 06:00",
                        "temp_c": 5.2,
                        "temp_f": 41.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
                            "code": 1135
                        },
                        "wind_mph": 7.2,
                        "wind_kph": 11.5,
                        "wind_degree": 261,
                        "wind_dir": "W",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.15,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 98,
                        "cloud": 100,
                        "feelslike_c": 3.1,
                        "feelslike_f": 37.6,
                        "windchill_c": 3.1,
                        "windchill_f": 37.6,
                        "heatindex_c": 5.2,
                        "heatindex_f": 41.4,
                        "dewpoint_c": 5.0,
                        "dewpoint_f": 41.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.6,
                        "gust_kph": 15.5,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665313200,
                        "time": "2022-10-09 07:00",
                        "temp_c": 5.0,
                        "temp_f": 41.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
                            "code": 1135
                        },
                        "wind_mph": 8.1,
                        "wind_kph": 13.0,
                        "wind_degree": 254,
                        "wind_dir": "WSW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.15,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 99,
                        "cloud": 100,
                        "feelslike_c": 2.8,
                        "feelslike_f": 37.0,
                        "windchill_c": 2.8,
                        "windchill_f": 37.0,
                        "heatindex_c": 5.0,
                        "heatindex_f": 41.0,
                        "dewpoint_c": 4.8,
                        "dewpoint_f": 40.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.7,
                        "gust_kph": 17.3,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665316800,
                        "time": "2022-10-09 08:00",
                        "temp_c": 5.1,
                        "temp_f": 41.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
                            "code": 1135
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 257,
                        "wind_dir": "WSW",
                        "pressure_mb": 1022.0,
                        "pressure_in": 30.17,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 98,
                        "cloud": 100,
                        "feelslike_c": 2.8,
                        "feelslike_f": 37.0,
                        "windchill_c": 2.8,
                        "windchill_f": 37.0,
                        "heatindex_c": 5.1,
                        "heatindex_f": 41.2,
                        "dewpoint_c": 4.8,
                        "dewpoint_f": 40.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.5,
                        "gust_kph": 20.2,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1665320400,
                        "time": "2022-10-09 09:00",
                        "temp_c": 5.5,
                        "temp_f": 41.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
                            "code": 1135
                        },
                        "wind_mph": 11.2,
                        "wind_kph": 18.0,
                        "wind_degree": 259,
                        "wind_dir": "W",
                        "pressure_mb": 1022.0,
                        "pressure_in": 30.18,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 97,
                        "cloud": 100,
                        "feelslike_c": 3.2,
                        "feelslike_f": 37.8,
                        "windchill_c": 3.2,
                        "windchill_f": 37.8,
                        "heatindex_c": 5.5,
                        "heatindex_f": 41.9,
                        "dewpoint_c": 5.1,
                        "dewpoint_f": 41.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.9,
                        "gust_kph": 22.3,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1665324000,
                        "time": "2022-10-09 10:00",
                        "temp_c": 6.2,
                        "temp_f": 43.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Mist",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/143.png",
                            "code": 1030
                        },
                        "wind_mph": 12.5,
                        "wind_kph": 20.2,
                        "wind_degree": 255,
                        "wind_dir": "WSW",
                        "pressure_mb": 1022.0,
                        "pressure_in": 30.18,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 95,
                        "cloud": 100,
                        "feelslike_c": 3.8,
                        "feelslike_f": 38.8,
                        "windchill_c": 3.8,
                        "windchill_f": 38.8,
                        "heatindex_c": 6.2,
                        "heatindex_f": 43.2,
                        "dewpoint_c": 5.5,
                        "dewpoint_f": 41.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 14.8,
                        "gust_kph": 23.8,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1665327600,
                        "time": "2022-10-09 11:00",
                        "temp_c": 9.0,
                        "temp_f": 48.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 13.4,
                        "wind_kph": 21.6,
                        "wind_degree": 253,
                        "wind_dir": "WSW",
                        "pressure_mb": 1022.0,
                        "pressure_in": 30.17,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 83,
                        "cloud": 36,
                        "feelslike_c": 6.9,
                        "feelslike_f": 44.4,
                        "windchill_c": 6.9,
                        "windchill_f": 44.4,
                        "heatindex_c": 9.0,
                        "heatindex_f": 48.2,
                        "dewpoint_c": 6.3,
                        "dewpoint_f": 43.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.4,
                        "gust_kph": 24.8,
                        "uv": 3.0
                    },
                    {
                        "time_epoch": 1665331200,
                        "time": "2022-10-09 12:00",
                        "temp_c": 11.9,
                        "temp_f": 53.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 13.9,
                        "wind_kph": 22.3,
                        "wind_degree": 255,
                        "wind_dir": "WSW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.14,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 70,
                        "cloud": 7,
                        "feelslike_c": 10.1,
                        "feelslike_f": 50.2,
                        "windchill_c": 10.1,
                        "windchill_f": 50.2,
                        "heatindex_c": 11.9,
                        "heatindex_f": 53.4,
                        "dewpoint_c": 6.7,
                        "dewpoint_f": 44.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.9,
                        "gust_kph": 25.6,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1665334800,
                        "time": "2022-10-09 13:00",
                        "temp_c": 13.9,
                        "temp_f": 57.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 14.3,
                        "wind_kph": 23.0,
                        "wind_degree": 264,
                        "wind_dir": "W",
                        "pressure_mb": 1020.0,
                        "pressure_in": 30.12,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 64,
                        "cloud": 0,
                        "feelslike_c": 12.4,
                        "feelslike_f": 54.3,
                        "windchill_c": 12.4,
                        "windchill_f": 54.3,
                        "heatindex_c": 13.9,
                        "heatindex_f": 57.0,
                        "dewpoint_c": 7.2,
                        "dewpoint_f": 45.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 16.6,
                        "gust_kph": 26.6,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1665338400,
                        "time": "2022-10-09 14:00",
                        "temp_c": 14.7,
                        "temp_f": 58.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 14.3,
                        "wind_kph": 23.0,
                        "wind_degree": 271,
                        "wind_dir": "W",
                        "pressure_mb": 1020.0,
                        "pressure_in": 30.11,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 59,
                        "cloud": 0,
                        "feelslike_c": 13.3,
                        "feelslike_f": 55.9,
                        "windchill_c": 13.3,
                        "windchill_f": 55.9,
                        "heatindex_c": 14.7,
                        "heatindex_f": 58.5,
                        "dewpoint_c": 6.8,
                        "dewpoint_f": 44.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 16.6,
                        "gust_kph": 26.6,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1665342000,
                        "time": "2022-10-09 15:00",
                        "temp_c": 15.0,
                        "temp_f": 59.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 14.1,
                        "wind_kph": 22.7,
                        "wind_degree": 267,
                        "wind_dir": "W",
                        "pressure_mb": 1019.0,
                        "pressure_in": 30.1,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 56,
                        "cloud": 0,
                        "feelslike_c": 13.7,
                        "feelslike_f": 56.7,
                        "windchill_c": 13.7,
                        "windchill_f": 56.7,
                        "heatindex_c": 15.0,
                        "heatindex_f": 59.0,
                        "dewpoint_c": 6.3,
                        "dewpoint_f": 43.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 16.1,
                        "gust_kph": 25.9,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1665345600,
                        "time": "2022-10-09 16:00",
                        "temp_c": 15.4,
                        "temp_f": 59.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 13.9,
                        "wind_kph": 22.3,
                        "wind_degree": 269,
                        "wind_dir": "W",
                        "pressure_mb": 1019.0,
                        "pressure_in": 30.09,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 55,
                        "cloud": 0,
                        "feelslike_c": 15.4,
                        "feelslike_f": 59.7,
                        "windchill_c": 15.4,
                        "windchill_f": 59.7,
                        "heatindex_c": 15.4,
                        "heatindex_f": 59.7,
                        "dewpoint_c": 6.4,
                        "dewpoint_f": 43.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.9,
                        "gust_kph": 25.6,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1665349200,
                        "time": "2022-10-09 17:00",
                        "temp_c": 15.5,
                        "temp_f": 59.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 13.9,
                        "wind_kph": 22.3,
                        "wind_degree": 275,
                        "wind_dir": "W",
                        "pressure_mb": 1019.0,
                        "pressure_in": 30.09,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 57,
                        "cloud": 0,
                        "feelslike_c": 15.5,
                        "feelslike_f": 59.9,
                        "windchill_c": 15.5,
                        "windchill_f": 59.9,
                        "heatindex_c": 15.5,
                        "heatindex_f": 59.9,
                        "dewpoint_c": 6.9,
                        "dewpoint_f": 44.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.9,
                        "gust_kph": 25.6,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1665352800,
                        "time": "2022-10-09 18:00",
                        "temp_c": 15.4,
                        "temp_f": 59.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 12.8,
                        "wind_kph": 20.5,
                        "wind_degree": 276,
                        "wind_dir": "W",
                        "pressure_mb": 1020.0,
                        "pressure_in": 30.11,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 63,
                        "cloud": 0,
                        "feelslike_c": 15.4,
                        "feelslike_f": 59.7,
                        "windchill_c": 15.4,
                        "windchill_f": 59.7,
                        "heatindex_c": 15.4,
                        "heatindex_f": 59.7,
                        "dewpoint_c": 8.3,
                        "dewpoint_f": 46.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 16.3,
                        "gust_kph": 26.3,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1665356400,
                        "time": "2022-10-09 19:00",
                        "temp_c": 15.5,
                        "temp_f": 59.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 10.7,
                        "wind_kph": 17.3,
                        "wind_degree": 272,
                        "wind_dir": "W",
                        "pressure_mb": 1020.0,
                        "pressure_in": 30.12,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 68,
                        "cloud": 0,
                        "feelslike_c": 15.5,
                        "feelslike_f": 59.9,
                        "windchill_c": 15.5,
                        "windchill_f": 59.9,
                        "heatindex_c": 15.5,
                        "heatindex_f": 59.9,
                        "dewpoint_c": 9.6,
                        "dewpoint_f": 49.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.2,
                        "gust_kph": 21.2,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665360000,
                        "time": "2022-10-09 20:00",
                        "temp_c": 12.8,
                        "temp_f": 55.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 262,
                        "wind_dir": "W",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.14,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 71,
                        "cloud": 0,
                        "feelslike_c": 11.3,
                        "feelslike_f": 52.3,
                        "windchill_c": 11.3,
                        "windchill_f": 52.3,
                        "heatindex_c": 12.8,
                        "heatindex_f": 55.0,
                        "dewpoint_c": 7.6,
                        "dewpoint_f": 45.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.2,
                        "gust_kph": 21.2,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665363600,
                        "time": "2022-10-09 21:00",
                        "temp_c": 12.5,
                        "temp_f": 54.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.9,
                        "wind_kph": 14.4,
                        "wind_degree": 257,
                        "wind_dir": "WSW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.14,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 73,
                        "cloud": 0,
                        "feelslike_c": 11.0,
                        "feelslike_f": 51.8,
                        "windchill_c": 11.0,
                        "windchill_f": 51.8,
                        "heatindex_c": 12.5,
                        "heatindex_f": 54.5,
                        "dewpoint_c": 7.7,
                        "dewpoint_f": 45.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.5,
                        "gust_kph": 20.2,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665367200,
                        "time": "2022-10-09 22:00",
                        "temp_c": 12.2,
                        "temp_f": 54.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.7,
                        "wind_kph": 14.0,
                        "wind_degree": 252,
                        "wind_dir": "WSW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.14,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 74,
                        "cloud": 0,
                        "feelslike_c": 10.8,
                        "feelslike_f": 51.4,
                        "windchill_c": 10.8,
                        "windchill_f": 51.4,
                        "heatindex_c": 12.2,
                        "heatindex_f": 54.0,
                        "dewpoint_c": 7.6,
                        "dewpoint_f": 45.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.3,
                        "gust_kph": 19.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665370800,
                        "time": "2022-10-09 23:00",
                        "temp_c": 11.9,
                        "temp_f": 53.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.2,
                        "wind_kph": 14.8,
                        "wind_degree": 246,
                        "wind_dir": "WSW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.15,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 75,
                        "cloud": 0,
                        "feelslike_c": 10.6,
                        "feelslike_f": 51.1,
                        "windchill_c": 10.6,
                        "windchill_f": 51.1,
                        "heatindex_c": 11.9,
                        "heatindex_f": 53.4,
                        "dewpoint_c": 7.6,
                        "dewpoint_f": 45.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.8,
                        "gust_kph": 20.5,
                        "uv": 1.0
                    }
                ]
            },
            {
                "date": "2022-10-17",
                "date_epoch": 1665360000,
                "day": {
                    "maxtemp_c": 19.5,
                    "maxtemp_f": 67.1,
                    "mintemp_c": 8.9,
                    "mintemp_f": 48.0,
                    "avgtemp_c": 14.4,
                    "avgtemp_f": 58.0,
                    "maxwind_mph": 10.3,
                    "maxwind_kph": 16.6,
                    "totalprecip_mm": 0.0,
                    "totalprecip_in": 0.0,
                    "avgvis_km": 10.0,
                    "avgvis_miles": 6.0,
                    "avghumidity": 65.0,
                    "daily_will_it_rain": 0,
                    "daily_chance_of_rain": 0,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "uv": 4.0
                },
                "astro": {
                    "sunrise": "07:02 AM",
                    "sunset": "06:23 PM",
                    "moonrise": "06:58 PM",
                    "moonset": "07:42 AM",
                    "moon_phase": "Full Moon",
                    "moon_illumination": "100"
                },
                "hour": [
                    {
                        "time_epoch": 1665374400,
                        "time": "2022-10-10 00:00",
                        "temp_c": 11.4,
                        "temp_f": 52.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 242,
                        "wind_dir": "WSW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.14,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 77,
                        "cloud": 0,
                        "feelslike_c": 10.1,
                        "feelslike_f": 50.2,
                        "windchill_c": 10.1,
                        "windchill_f": 50.2,
                        "heatindex_c": 11.4,
                        "heatindex_f": 52.5,
                        "dewpoint_c": 7.5,
                        "dewpoint_f": 45.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.6,
                        "gust_kph": 22.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665378000,
                        "time": "2022-10-10 01:00",
                        "temp_c": 11.1,
                        "temp_f": 52.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 245,
                        "wind_dir": "WSW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.14,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 78,
                        "cloud": 0,
                        "feelslike_c": 9.9,
                        "feelslike_f": 49.8,
                        "windchill_c": 9.9,
                        "windchill_f": 49.8,
                        "heatindex_c": 11.1,
                        "heatindex_f": 52.0,
                        "dewpoint_c": 7.5,
                        "dewpoint_f": 45.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.6,
                        "gust_kph": 22.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665381600,
                        "time": "2022-10-10 02:00",
                        "temp_c": 10.7,
                        "temp_f": 51.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.2,
                        "wind_kph": 14.8,
                        "wind_degree": 250,
                        "wind_dir": "WSW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.15,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 80,
                        "cloud": 0,
                        "feelslike_c": 9.4,
                        "feelslike_f": 48.9,
                        "windchill_c": 9.4,
                        "windchill_f": 48.9,
                        "heatindex_c": 10.7,
                        "heatindex_f": 51.3,
                        "dewpoint_c": 7.4,
                        "dewpoint_f": 45.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.2,
                        "gust_kph": 21.2,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665385200,
                        "time": "2022-10-10 03:00",
                        "temp_c": 10.2,
                        "temp_f": 50.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.7,
                        "wind_kph": 14.0,
                        "wind_degree": 255,
                        "wind_dir": "WSW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.15,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 83,
                        "cloud": 0,
                        "feelslike_c": 8.9,
                        "feelslike_f": 48.0,
                        "windchill_c": 8.9,
                        "windchill_f": 48.0,
                        "heatindex_c": 10.2,
                        "heatindex_f": 50.4,
                        "dewpoint_c": 7.4,
                        "dewpoint_f": 45.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.3,
                        "gust_kph": 19.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665388800,
                        "time": "2022-10-10 04:00",
                        "temp_c": 9.7,
                        "temp_f": 49.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.5,
                        "wind_kph": 13.7,
                        "wind_degree": 257,
                        "wind_dir": "WSW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.15,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 86,
                        "cloud": 0,
                        "feelslike_c": 8.4,
                        "feelslike_f": 47.1,
                        "windchill_c": 8.4,
                        "windchill_f": 47.1,
                        "heatindex_c": 9.7,
                        "heatindex_f": 49.5,
                        "dewpoint_c": 7.5,
                        "dewpoint_f": 45.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.3,
                        "gust_kph": 19.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665392400,
                        "time": "2022-10-10 05:00",
                        "temp_c": 9.3,
                        "temp_f": 48.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.5,
                        "wind_kph": 13.7,
                        "wind_degree": 257,
                        "wind_dir": "WSW",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.16,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 89,
                        "cloud": 0,
                        "feelslike_c": 8.2,
                        "feelslike_f": 46.8,
                        "windchill_c": 8.2,
                        "windchill_f": 46.8,
                        "heatindex_c": 9.3,
                        "heatindex_f": 48.7,
                        "dewpoint_c": 7.6,
                        "dewpoint_f": 45.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.1,
                        "gust_kph": 19.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665396000,
                        "time": "2022-10-10 06:00",
                        "temp_c": 9.1,
                        "temp_f": 48.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.1,
                        "wind_kph": 13.0,
                        "wind_degree": 258,
                        "wind_dir": "WSW",
                        "pressure_mb": 1022.0,
                        "pressure_in": 30.17,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 90,
                        "cloud": 0,
                        "feelslike_c": 8.2,
                        "feelslike_f": 46.8,
                        "windchill_c": 8.2,
                        "windchill_f": 46.8,
                        "heatindex_c": 9.1,
                        "heatindex_f": 48.4,
                        "dewpoint_c": 7.5,
                        "dewpoint_f": 45.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.6,
                        "gust_kph": 18.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665399600,
                        "time": "2022-10-10 07:00",
                        "temp_c": 8.9,
                        "temp_f": 48.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.1,
                        "wind_kph": 13.0,
                        "wind_degree": 258,
                        "wind_dir": "WSW",
                        "pressure_mb": 1022.0,
                        "pressure_in": 30.19,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 91,
                        "cloud": 0,
                        "feelslike_c": 8.0,
                        "feelslike_f": 46.4,
                        "windchill_c": 8.0,
                        "windchill_f": 46.4,
                        "heatindex_c": 8.9,
                        "heatindex_f": 48.0,
                        "dewpoint_c": 7.4,
                        "dewpoint_f": 45.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.4,
                        "gust_kph": 18.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665403200,
                        "time": "2022-10-10 08:00",
                        "temp_c": 9.0,
                        "temp_f": 48.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.1,
                        "wind_kph": 13.0,
                        "wind_degree": 257,
                        "wind_dir": "WSW",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.2,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 88,
                        "cloud": 2,
                        "feelslike_c": 7.9,
                        "feelslike_f": 46.2,
                        "windchill_c": 7.9,
                        "windchill_f": 46.2,
                        "heatindex_c": 9.0,
                        "heatindex_f": 48.2,
                        "dewpoint_c": 7.0,
                        "dewpoint_f": 44.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.0,
                        "gust_kph": 17.6,
                        "uv": 3.0
                    },
                    {
                        "time_epoch": 1665406800,
                        "time": "2022-10-10 09:00",
                        "temp_c": 10.5,
                        "temp_f": 50.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.5,
                        "wind_kph": 13.7,
                        "wind_degree": 259,
                        "wind_dir": "W",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.21,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 78,
                        "cloud": 0,
                        "feelslike_c": 9.7,
                        "feelslike_f": 49.5,
                        "windchill_c": 9.7,
                        "windchill_f": 49.5,
                        "heatindex_c": 10.5,
                        "heatindex_f": 50.9,
                        "dewpoint_c": 6.8,
                        "dewpoint_f": 44.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.0,
                        "gust_kph": 17.6,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1665410400,
                        "time": "2022-10-10 10:00",
                        "temp_c": 12.6,
                        "temp_f": 54.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.9,
                        "wind_kph": 14.4,
                        "wind_degree": 259,
                        "wind_dir": "W",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.21,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 67,
                        "cloud": 0,
                        "feelslike_c": 12.1,
                        "feelslike_f": 53.8,
                        "windchill_c": 12.1,
                        "windchill_f": 53.8,
                        "heatindex_c": 12.6,
                        "heatindex_f": 54.7,
                        "dewpoint_c": 6.7,
                        "dewpoint_f": 44.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.0,
                        "gust_kph": 17.6,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1665414000,
                        "time": "2022-10-10 11:00",
                        "temp_c": 17.0,
                        "temp_f": 62.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.8,
                        "wind_kph": 15.8,
                        "wind_degree": 256,
                        "wind_dir": "WSW",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.21,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 58,
                        "cloud": 0,
                        "feelslike_c": 17.0,
                        "feelslike_f": 62.6,
                        "windchill_c": 17.0,
                        "windchill_f": 62.6,
                        "heatindex_c": 17.0,
                        "heatindex_f": 62.6,
                        "dewpoint_c": 8.8,
                        "dewpoint_f": 47.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.4,
                        "gust_kph": 18.4,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1665417600,
                        "time": "2022-10-10 12:00",
                        "temp_c": 18.0,
                        "temp_f": 64.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 10.3,
                        "wind_kph": 16.6,
                        "wind_degree": 256,
                        "wind_dir": "WSW",
                        "pressure_mb": 1022.0,
                        "pressure_in": 30.19,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 53,
                        "cloud": 0,
                        "feelslike_c": 18.0,
                        "feelslike_f": 64.4,
                        "windchill_c": 18.0,
                        "windchill_f": 64.4,
                        "heatindex_c": 18.0,
                        "heatindex_f": 64.4,
                        "dewpoint_c": 8.4,
                        "dewpoint_f": 47.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.9,
                        "gust_kph": 19.1,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1665421200,
                        "time": "2022-10-10 13:00",
                        "temp_c": 18.6,
                        "temp_f": 65.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 10.1,
                        "wind_kph": 16.2,
                        "wind_degree": 254,
                        "wind_dir": "WSW",
                        "pressure_mb": 1022.0,
                        "pressure_in": 30.17,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 50,
                        "cloud": 0,
                        "feelslike_c": 18.6,
                        "feelslike_f": 65.5,
                        "windchill_c": 18.6,
                        "windchill_f": 65.5,
                        "heatindex_c": 18.6,
                        "heatindex_f": 65.5,
                        "dewpoint_c": 7.9,
                        "dewpoint_f": 46.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.6,
                        "gust_kph": 18.7,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1665424800,
                        "time": "2022-10-10 14:00",
                        "temp_c": 19.0,
                        "temp_f": 66.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 10.3,
                        "wind_kph": 16.6,
                        "wind_degree": 258,
                        "wind_dir": "WSW",
                        "pressure_mb": 1022.0,
                        "pressure_in": 30.17,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 48,
                        "cloud": 0,
                        "feelslike_c": 19.0,
                        "feelslike_f": 66.2,
                        "windchill_c": 19.0,
                        "windchill_f": 66.2,
                        "heatindex_c": 19.0,
                        "heatindex_f": 66.2,
                        "dewpoint_c": 7.6,
                        "dewpoint_f": 45.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.9,
                        "gust_kph": 19.1,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1665428400,
                        "time": "2022-10-10 15:00",
                        "temp_c": 19.5,
                        "temp_f": 67.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 10.3,
                        "wind_kph": 16.6,
                        "wind_degree": 266,
                        "wind_dir": "W",
                        "pressure_mb": 1022.0,
                        "pressure_in": 30.18,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 36,
                        "cloud": 25,
                        "feelslike_c": 19.5,
                        "feelslike_f": 67.1,
                        "windchill_c": 19.5,
                        "windchill_f": 67.1,
                        "heatindex_c": 19.5,
                        "heatindex_f": 67.1,
                        "dewpoint_c": 4.0,
                        "dewpoint_f": 39.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.9,
                        "gust_kph": 19.1,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1665432000,
                        "time": "2022-10-10 16:00",
                        "temp_c": 19.4,
                        "temp_f": 66.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 10.1,
                        "wind_kph": 16.2,
                        "wind_degree": 275,
                        "wind_dir": "W",
                        "pressure_mb": 1022.0,
                        "pressure_in": 30.18,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 38,
                        "cloud": 46,
                        "feelslike_c": 19.4,
                        "feelslike_f": 66.9,
                        "windchill_c": 19.4,
                        "windchill_f": 66.9,
                        "heatindex_c": 19.4,
                        "heatindex_f": 66.9,
                        "dewpoint_c": 4.9,
                        "dewpoint_f": 40.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.1,
                        "gust_kph": 19.4,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1665435600,
                        "time": "2022-10-10 17:00",
                        "temp_c": 18.5,
                        "temp_f": 65.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.8,
                        "wind_kph": 15.8,
                        "wind_degree": 283,
                        "wind_dir": "WNW",
                        "pressure_mb": 1022.0,
                        "pressure_in": 30.16,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 53,
                        "cloud": 17,
                        "feelslike_c": 18.5,
                        "feelslike_f": 65.3,
                        "windchill_c": 18.5,
                        "windchill_f": 65.3,
                        "heatindex_c": 18.5,
                        "heatindex_f": 65.3,
                        "dewpoint_c": 8.8,
                        "dewpoint_f": 47.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.0,
                        "gust_kph": 20.9,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1665439200,
                        "time": "2022-10-10 18:00",
                        "temp_c": 19.2,
                        "temp_f": 66.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 7.8,
                        "wind_kph": 12.6,
                        "wind_degree": 290,
                        "wind_dir": "WNW",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.2,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 42,
                        "cloud": 32,
                        "feelslike_c": 19.2,
                        "feelslike_f": 66.6,
                        "windchill_c": 19.2,
                        "windchill_f": 66.6,
                        "heatindex_c": 19.2,
                        "heatindex_f": 66.6,
                        "dewpoint_c": 5.9,
                        "dewpoint_f": 42.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.6,
                        "gust_kph": 15.5,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1665442800,
                        "time": "2022-10-10 19:00",
                        "temp_c": 18.8,
                        "temp_f": 65.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 5.4,
                        "wind_kph": 8.6,
                        "wind_degree": 290,
                        "wind_dir": "WNW",
                        "pressure_mb": 1024.0,
                        "pressure_in": 30.22,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 45,
                        "cloud": 43,
                        "feelslike_c": 18.8,
                        "feelslike_f": 65.8,
                        "windchill_c": 18.8,
                        "windchill_f": 65.8,
                        "heatindex_c": 18.8,
                        "heatindex_f": 65.8,
                        "dewpoint_c": 6.5,
                        "dewpoint_f": 43.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.7,
                        "gust_kph": 10.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665446400,
                        "time": "2022-10-10 20:00",
                        "temp_c": 16.3,
                        "temp_f": 61.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.8,
                        "wind_kph": 6.1,
                        "wind_degree": 280,
                        "wind_dir": "W",
                        "pressure_mb": 1022.0,
                        "pressure_in": 30.19,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 69,
                        "cloud": 12,
                        "feelslike_c": 16.3,
                        "feelslike_f": 61.3,
                        "windchill_c": 16.3,
                        "windchill_f": 61.3,
                        "heatindex_c": 16.3,
                        "heatindex_f": 61.3,
                        "dewpoint_c": 10.5,
                        "dewpoint_f": 50.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.4,
                        "gust_kph": 8.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665450000,
                        "time": "2022-10-10 21:00",
                        "temp_c": 17.5,
                        "temp_f": 63.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 4.0,
                        "wind_kph": 6.5,
                        "wind_degree": 275,
                        "wind_dir": "W",
                        "pressure_mb": 1025.0,
                        "pressure_in": 30.26,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 48,
                        "cloud": 32,
                        "feelslike_c": 17.5,
                        "feelslike_f": 63.5,
                        "windchill_c": 17.5,
                        "windchill_f": 63.5,
                        "heatindex_c": 17.5,
                        "heatindex_f": 63.5,
                        "dewpoint_c": 6.3,
                        "dewpoint_f": 43.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.4,
                        "gust_kph": 8.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665453600,
                        "time": "2022-10-10 22:00",
                        "temp_c": 17.0,
                        "temp_f": 62.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.6,
                        "wind_kph": 5.8,
                        "wind_degree": 294,
                        "wind_dir": "WNW",
                        "pressure_mb": 1025.0,
                        "pressure_in": 30.27,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 50,
                        "cloud": 24,
                        "feelslike_c": 17.0,
                        "feelslike_f": 62.6,
                        "windchill_c": 17.0,
                        "windchill_f": 62.6,
                        "heatindex_c": 17.0,
                        "heatindex_f": 62.6,
                        "dewpoint_c": 6.5,
                        "dewpoint_f": 43.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.9,
                        "gust_kph": 7.9,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1665457200,
                        "time": "2022-10-10 23:00",
                        "temp_c": 15.4,
                        "temp_f": 59.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                            "code": 1006
                        },
                        "wind_mph": 1.8,
                        "wind_kph": 2.9,
                        "wind_degree": 283,
                        "wind_dir": "WNW",
                        "pressure_mb": 1024.0,
                        "pressure_in": 30.22,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 73,
                        "cloud": 65,
                        "feelslike_c": 15.4,
                        "feelslike_f": 59.7,
                        "windchill_c": 15.4,
                        "windchill_f": 59.7,
                        "heatindex_c": 15.4,
                        "heatindex_f": 59.7,
                        "dewpoint_c": 10.7,
                        "dewpoint_f": 51.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 2.5,
                        "gust_kph": 4.0,
                        "uv": 1.0
                    }
                ]
            }
        ]
    }
}